imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        projects_interval: 5000
        projects_animation_speed: 1000
        slideshow_interval: 1000
        slideshow_animation_speed: 1000

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
# Stoff Doctrine Extensions Configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            
# Vich Uploader Configuration
vich_uploader:
    db_driver: orm
    twig: true
    mappings:
        gallery_image:
            upload_destination: %kernel.root_dir%/../web/img/uploads/gallery-images
            delete_on_remove: true
            inject_on_load: true
            namer: imgnamer.service

#Liip Imagine Configuration
liip_imagine:
    driver:               gd
    web_root:             %kernel.root_dir%/../web
    #data_root:            %liip_imagine.web_root%
    cache_prefix:         /media/cache
    cache:                web_path
    data_loader:          filesystem
    controller_action:    liip_imagine.controller:filterAction
    formats:              []
    filter_sets:
        slideshow_thumb:
            quality: 100
            path: /slideshow-thumbs/
            filters:
                thumbnail: { size: [310, 165], mode: outbound }
        slideshow_slide:
            quality: 100
            path: /slideshow-slides/
            filters:
                thumbnail: { size: [650, 360], mode: outbound }
        project_thumb:
            quality: 100
            path: /project-thumbs/
            filters:
                thumbnail: { size: [300, 170], mode: outbound }