services:
    security.access.blacklist_voter:
          class: Fish\UserBundle\Security\Authorization\Voter\ClientIpVoter
          arguments: [@service_container]
          public: false
          tags:
              - { name: security.voter }